# Ashron Configuration File

# Provider settings (openai, anthropic, custom)
provider: openai

# API Configuration
api:
  base_url: https://api.openai.com/v1
  # api_key: YOUR_API_KEY_HERE  # Can also use OPENAI_API_KEY env var
  model: gpt-4-turbo-preview
  max_tokens: 4096
  temperature: 0.7

# Tools Configuration
tools:
  # Commands that don't require approval
  auto_approve:
    - read_file
    - list_directory
    - get_working_directory
  max_output_size: 50000  # Maximum bytes for command output
  command_timeout: 30     # Seconds

# Context Management
context:
  max_messages: 50
  max_tokens: 100000
  compaction_ratio: 0.5  # Compact when context uses more than 50 percent of max tokens
  auto_compact: true